
/control/verbose 0
/run/verbose 0
/tracking/verbose 0
#
/run/initialize
#
/gun/particle ion
/gun/ion 27 57
#
/control/execute vis.mac
#
/analysis/setFileName rdecay02
/analysis/h1/set 0 100 0. 2. MeV
/analysis/h1/set 1 100 0. 2. MeV
/analysis/h1/set 2 100 0. 2. MeV
/analysis/h1/set 3 100 0. 2. MeV
/analysis/h1/set 4 100 0. 2. MeV
/analysis/h1/set 5 100 0. 2. MeV
/analysis/h1/set 6 100 0. 2. MeV
#
/run/beamOn 10000
