#!/usr/bin/python3.5

import matplotlib.pyplot as plt
from matplotlib import cm
import pandas as pd
import numpy as np
from astroML.stats import fit_bivariate_normal
import sys

from fncs.fnc_getDetectorHitData import getDetectorHitData

X1, Y1 = getDetectorHitData(detector=1)


fig = plt.figure()
fig.subplots_adjust(left=0.09, right=0.95, wspace=0.0,
                bottom=0.10, top=0.94)
ax = fig.add_subplot(1,1,1)


# Creates histogram from hit data, look into auto bin number
counts,xbins,ybins,image = plt.hist2d(X1,Y1, bins=300, normed=True)

norm = cm.colors.Normalize(vmax=max(abs(X1).max(), abs(Y1).max()), vmin=-max(abs(X1).max(), abs(Y1).max()))

plt.contour(counts.transpose(),extent=[xbins.min(),xbins.max(),ybins.min(),ybins.max()],linewidths=1, norm=norm)
plt.xlim([-6,6]); plt.xlabel("x [cm]")
plt.ylim([-6,6]); plt.ylabel("z [cm]")
plt.title("Detector 1")


plt.show()
